var vg_1 = "js/nostalgia_matrix.vg.json";
vegaEmbed("#nostalgia_matrix", vg_1).catch(console.error);
var vg_2 = "js/fleet_age_map.vg.json";
vegaEmbed("#fleet_age_map", vg_2).catch(console.error);
var vg_3 = "js/fleet_symbol_map.vg.json";
vegaEmbed("#fleet_symbol_map", vg_3).catch(console.error);
var vg_4 = "js/ev_hex_map.vg.json";
vegaEmbed("#ev_hex_map", vg_4).catch(console.error);
var vg_5 = "js/designer_timeline.vg.json";
vegaEmbed("#designer_timeline", vg_5).catch(console.error);
var vg_6 = "js/designer_bump.vg.json";
vegaEmbed("#designer_bump", vg_6).catch(console.error);
var vg_7 = "js/decade_butterfly.vg.json";
vegaEmbed("#decade_butterfly", vg_7).catch(console.error);
var vg_8 = "js/decade_waffle.vg.json";
vegaEmbed("#decade_waffle", vg_8).catch(console.error);
var vg_9 = "js/decade_gap.vg.json";
vegaEmbed("#decade_gap", vg_9).catch(console.error);